steps:
  # Step 1: Checkout the source code
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/HarshJain975/hello-python-app.git']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/elite-flow-446700-k5/python-app:$SHORT_SHA'
      - '.'

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/elite-flow-446700-k5/python-app:$SHORT_SHA'

  # Step 4: Deploy the Docker image to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'hello-python'
      - '--region'
      - 'us-central1'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/python-app'
      - 'python-app=gcr.io/elite-flow-446700-k5/python-app:$SHORT_SHA'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/python-app'

images:
  - 'gcr.io/elite-flow-446700-k5/python-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
