steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/atomic-segment-442210-n3/hello-repo/hello-python-app', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/atomic-segment-442210-n3/hello-repo/hello-python-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'hello-private-cluster'
      - '--region'
      - 'us-central1'  # Use the region instead of a zone
      - '--project'
      - 'atomic-segment-442210-n3'

  # SSH into Bastion VM and run kubectl commands to apply deployment and service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'bastion-host'  # Replace with your Bastion VM name
      - '--project'
      - 'atomic-segment-442210-n3'
      - '--zone'
      - 'us-central1-a'  # Replace with your Bastion VM zone
      - '--command'
      - |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET


