apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: hello-python
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
